services:
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    env_file: .env
    restart: always
    ports:
      - "8000:3000"
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"